config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :chatrooms do
    #resource :chatroom_users
    resource :chatroom_users
    resources :messages
  end
  root to: 'chatrooms#index'
  #root 'site#index'
  get 'site/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :chatroom_users
  has_many :users, through: :chatroom_users
  has_many :messages
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/chatroom_users_controller.rb
class ChatroomUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom

  def create
    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
    redirect_to @chatroom
  end

  def destroy
    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).destroy_all
    redirect_to chatrooms_path
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:chatroom_id])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: %i[ show edit update destroy ]

  # GET /chatrooms or /chatrooms.json
  def index
    @chatrooms = Chatroom.all
  end

  # GET /chatrooms/1 or /chatrooms/1.json
  def show
    @messages = @chatroom.messages.order(created_at: :desc).limit(100).reverse
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms or /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to chatroom_url(@chatroom), notice: "Chatroom was successfully created." }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1 or /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to chatroom_url(@chatroom), notice: "Chatroom was successfully updated." }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1 or /chatrooms/1.json
  def destroy
    @chatroom.destroy!

    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: "Chatroom was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chatroom


  def create
    @message = @chatroom.messages.create(message_params)
    #message.user = current_user
    #message.save
    #redirect_to @chatroom

    #MessageRelayJob.perform_later(message)
    #ChatroomsChannel.broadcast_to("chatrooms:#{message.chatroom.id}", {

    #이게 chatrooms:chatrooms:2 뭐 이런 식으로 해석되어버림....ㅠㅠ
    #ChatroomsChannel.broadcast_to("#{message.chatroom.id}", {
      #username: message.user.username,
      #body: message.body,
      #chatroom_id: message.chatroom.id
    #})
    ChatroomsChannel.broadcast_to @chatroom, { message: render_to_string(@message) }
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:chatroom_id])
  end

  def message_params
    params.require(:message).permit(:body).merge(user: current_user)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/chatrooms/_chatroom.html.erb
<div data-controller="chatroom" data-chatroom-id="<%= @chatroom.id %>">
  <p>
    <strong>Name:</strong>
    <%= chatroom.name %>
  </p>

  <div data-chatroom-target="messages">
    <%= render @messages %>
  </div>

  <% if user_signed_in? %>
    <div>
      <%= form_with model: [@chatroom, Message.new], data: { action: "turbo:submit-end->chatroom#clearMessage" } do |f| %>
        <%#= f.text_area :body, rows: 1, data: {chatroom_target: "newMessage"}, class: "form-control", autofocus: true %>
        <!-- 뭔지 모르겠는데 이거 바꾸니까 data-action이 동작하기 시작함...ㅠㅠ -->
        <%= f.text_field :body, class: "form-control", data: {chatroom_target: "newMessage"} %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/chatrooms/_form.html.erb
<%= form_with(model: chatroom) do |form| %>
  <% if chatroom.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
        <% chatroom.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing chatroom</h1>

<%= render "form", chatroom: @chatroom %>

<br>

<div>
  <%= link_to "Show this chatroom", @chatroom %> |
  <%= link_to "Back to chatrooms", chatrooms_path %>
</div>

app/views/chatrooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Chatrooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @chatrooms.each do |chatroom| %>
      <tr>
        <td><%= chatroom.name %></td>
        <td>
          <%= link_to "Show this chatroom", chatroom %>
        </td>
        <td>
          <%= link_to "Join", chatroom_chatroom_users_path(chatroom), data: {turbo_method: :post} %>
        </td>
        <td>
          <%= link_to "Leave", chatroom_chatroom_users_path(chatroom), data: {turbo_method: :delete} %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>

<%= link_to "New chatroom", new_chatroom_path %>

app/views/chatrooms/new.html.erb
<h1>New chatroom</h1>

<%= render "form", chatroom: @chatroom %>

<br>

<div>
  <%= link_to "Back to chatrooms", chatrooms_path %>
</div>

app/views/chatrooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chatroom %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
      <div class="container-fluid">
        <%= link_to root_path, class: "navbar-brand" do %>
          Chat
        <% end %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>

          </ul>

          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <%= yield :right_nav %>

              <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                  <%= current_user.username %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                  <li><%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-success me-2" %></li>
              <li><%= link_to "Login", new_user_session_path, class: "btn btn-outline-secondary" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="fluid-container" style="margin-top: 70px">
      <div class="row">
        <div class="col-sm-2" style="position: fixed; top: 70px; left: 0">
          <% if user_signed_in? %>
            <h5>Chatrooms</h5>
            <ul>
              <% current_user.chatrooms.each do |chatroom| %>
                <li><%= link_to chatroom.name, chatroom %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
        <div class="col-sm-10 offset-sm-2">
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/messages/_message.html.erb
<div>
  <strong><%= message.user.username %>:</strong><%= message.body %>
</div>

app/views/site/index.html.erb
<h1>Site#index</h1>
<p>Find me in app/views/site/index.html.erb</p>